version: '2'
services:

    instance1-command-line-bootcamp-docker:
      image: docker:1.8-dind
      container_name: instance1-command-line-bootcamp-docker
      privileged: true

    instance1-command-line-bootcamp-term:
      image: fikipollo/cmd-bootcamp-term
      container_name: instance1-command-line-bootcamp-term
      links:
        - instance1-command-line-bootcamp-docker:docker
      depends_on:
        - instance1-command-line-bootcamp-docker
      ports:
        - "8093:8080"

    instance1-command-line-bootcamp-web:
      image: fikipollo/cmd-bootcamp-web
      container_name: instance1-command-line-bootcamp-web
      ports:
        - "8094:80"
      environment:
        - SERVER_URL=localhost:8093
