version: '2'
services:

    testbootcamp-docker:
      image: docker:1.8-dind
      container_name: testbootcamp-docker
      privileged: true

    testbootcamp-term:
      image: fikipollo/command-line-bootcamp:term
      container_name: testbootcamp-term
      links:
        - testbootcamp-docker:docker
      depends_on:
        - testbootcamp-docker
      ports:
        - "8093:8080"

    testbootcamp-web:
      image: fikipollo/command-line-bootcamp:web
      container_name: testbootcamp-web
      ports:
        - "8094:80"
      environment:
        - SERVER_URL="localhost:8093"
