FROM alpine

apk update \
    && apk add --no-cache curl make gcc g++ python linux-headers paxctl libgcc libstdc++ gnupg nano bash \
    && apk add nodejs \
    && apk add git

adduser -h /home/learner -s /bin/bash -D learner

# become the learner
USER learner
ENV HOME /home/learner
WORKDIR /home/learner

# install nvm
RUN cd && touch .bashrc \
    && curl https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

# change it to your required node version
ENV NODE_VERSION 5.1.0

# needed by nvm install
ENV NVM_DIR /home/learner/.nvm

# install the specified node version and set it as the default one, install the global npm packages
RUN . ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && npm install --global expose-fs

# expose the filesystem - needed for the file browser and editor
# in adventure time
RUN echo "expose-fs >> .fs.out 2>> .fs.err &" >> /home/learner/.bashrc

# more readable terminal prompt
RUN echo "export PS1=\"\[$(tput bold)\]\[\033[38;5;75m\]\u\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;232m\]@:\[$(tput sgr0)\]\[\033[38;5;9m\]\W\[$(tput sgr0)\]\[\033[38;5;232m\]\\$\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\"" >> /home/learner/.bashrc

# some example directories for the tutorial
RUN mkdir a_directory another_directory
